### ISSUE TITLE
Deleting from localStorage using ID of note in notes

### ISSUE THREAD

**Issue by anthonybui1** [peterphan20/notes-react-redux#1]
https://github.com/peterphan20/notes-react-redux/blob/777b0dfe1de8503edf538419e6711d891122c830/src/actions/index.js#L24

In localStorage, the key is notes and value is set to a stringified object. You won't be able to do ID lookups or anything like that, you need to parse the JSON before deleting the note and setting the updated object.

**Comment by peterphan20** [comment]
Changed it so it deletes the note correctly
