### ISSUE TITLE
Object.assign will only create a shallow copy

### ISSUE THREAD

**Issue by anthonybui1** [peterphan20/notes-react-redux#3]
https://github.com/peterphan20/notes-react-redux/blob/ba7e9ef7bb1f7ab13084ac4a26846b532de27630/src/reducers/notes.js#L4

Recommend using something similar to below for a deep copy to prevent side effects

```
const newState = JSON.parse(JSON.stringify(notes));
```

**Comment by peterphan20** [comment]
Used JSON.parse and JSON.stringify instead of Object.assign to create a deep copy rather than a shallow copy.
